// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjjPpdBuDZy5XBaOj0SJKbw2iixtxbT-A',
    appId: '1:526763236381:web:9c939998c1c201b25c3af4',
    messagingSenderId: '526763236381',
    projectId: 'club-manager-2d108',
    authDomain: 'club-manager-2d108.firebaseapp.com',
    storageBucket: 'club-manager-2d108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsPM5M5QDKdA3V1Y9zCYfnaMdwOFmZI18',
    appId: '1:526763236381:android:907f77a449ccc65b5c3af4',
    messagingSenderId: '526763236381',
    projectId: 'club-manager-2d108',
    storageBucket: 'club-manager-2d108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KgMt3R_GhFAasvwDLx-Uwg0BQhcDGG8',
    appId: '1:526763236381:ios:c7b854b11de5ed4d5c3af4',
    messagingSenderId: '526763236381',
    projectId: 'club-manager-2d108',
    storageBucket: 'club-manager-2d108.appspot.com',
    iosClientId: '526763236381-l45ttroh770mab50l0e30anlgqn8sacj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_KgMt3R_GhFAasvwDLx-Uwg0BQhcDGG8',
    appId: '1:526763236381:ios:c7b854b11de5ed4d5c3af4',
    messagingSenderId: '526763236381',
    projectId: 'club-manager-2d108',
    storageBucket: 'club-manager-2d108.appspot.com',
    iosClientId: '526763236381-l45ttroh770mab50l0e30anlgqn8sacj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt_4tByzqZ-QEt2hwBFw1D2xSY5Tam4BA',
    appId: '1:526763236381:web:69c4d222bcb49bc25c3af4',
    messagingSenderId: '526763236381',
    projectId: 'club-manager-2d108',
    authDomain: 'club-manager-2d108.firebaseapp.com',
    storageBucket: 'club-manager-2d108.appspot.com',
  );

}